export const NIGERIAN_STATES_LGAS = {
  "Abia": ["Aba North", "Aba South", "Arochukwu", "Ohafia", "Umuahia North", "Umuahia South"],
  "Adamawa": ["Demsa", "Fufore", "Ganye", "Mubi North", "Mubi South", "Yola North", "Yola South"],
  "Akwa Ibom": ["Eket", "Ikot Ekpene", "Oron", "Uyo", "Abak", "Itu"],
  "Anambra": ["Awka North", "Awka South", "Onitsha North", "Onitsha South", "Nnewi North", "Nnewi South"],
  "Bauchi": ["Alkaleri", "Bauchi", "Katagum", "Misau", "Ningi", "Tafawa Balewa"],
  "Bayelsa": ["Brass", "Ekeremor", "Kolokuma/Opokuma", "Nembe", "Ogbia", "Yenagoa"],
  "Benue": ["Gboko", "Makurdi", "Otukpo", "Katsina-Ala", "Vandeikya"],
  "Borno": ["Bama", "BiU", "Gwoza", "Maiduguri", "Monguno", "Jere"],
  "Cross River": ["Calabar Municipal", "Calabar South", "Ikom", "Ogoja", "Obudu", "Ugep"],
  "Delta": ["Asaba", "Warri North", "Warri South", "Sapele", "Ughelli North", "Ughelli South"],
  "Ebonyi": ["Abakaliki", "Afikpo North", "Afikpo South", "Onicha", "Izzi"],
  "Edo": ["Benin City", "Oredo", "Esan North-East", "Esan West", "Etsako West", "Akoko-Edo"],
  "Ekiti": ["Ado-Ekiti", "Ikere", "Oye", "Ikole", "Ekiti West"],
  "Enugu": ["Enugu East", "Enugu North", "Enugu South", "Nsukka", "Udi", "Awgu"],
  "Gombe": ["Akko", "Balanga", "Billiri", "Gombe", "Kaltungo", "Yamaltu/Deba"],
  "Imo": ["Owerri Municipal", "Owerri North", "Owerri South", "Orlu", "Okigwe", "Mbaitoli"],
  "Jigawa": ["Dutse", "Hadejia", "Kazaure", "Gumel", "Ringim", "Birnin Kudu"],
  "Kaduna": ["Kaduna North", "Kaduna South", "Zaria", "Sabon Gari", "Chikun", "Kafanchan"],
  "Kano": ["Kano Municipal", "Fagge", "Gwale", "Dala", "Nassarawa", "Tarauni", "Kano City"],
  "Katsina": ["Katsina", "Daura", "Funtua", "Malumfashi", "Dutsin-Ma"],
  "Kebbi": ["Birnin Kebbi", "Argungu", "Yauri", "Zuru", "Jega"],
  "Kogi": ["Lokoja", "Okene", "Idah", "Dekina", "Kabba/Bunu"],
  "Kwara": ["Ilorin East", "Ilorin West", "Ilorin South", "Offa", "Edu", "Kaiama"],
  "Lagos": ["Ikeja", "Lekki", "Alimosho", "Lagos Island", "Lagos Mainland", "Surulere", "Epe", "Badagry"],
  "Nasarawa": ["Lafia", "Keffi", "Akwanga", "Karu", "Nasarawa"],
  "Niger": ["Minna", "Bida", "Suleja", "Kontagora", "Chanchaga"],
  "Ogun": ["Abeokuta North", "Abeokuta South", "Ijebu Ode", "Sagamu", "Ota", "Ilaro"],
  "Ondo": ["Akure North", "Akure South", "Owo", "Ondo West", "Okitipupa", "Ikare"],
  "Osun": ["Osogbo", "Ilesa East", "Ilesa West", "Ife Central", "Ife East", "Ede North"],
  "Oyo": ["Ibadan North", "Ibadan North-East", "Ibadan North-West", "Ibadan South-East", "Ibadan South-West", "Ogbomosho North", "Oyo East"],
  "Plateau": ["Jos North", "Jos South", "Jos East", "Bukuru", "Pankshin", "Shendam"],
  "Rivers": ["Port Harcourt", "Obio/Akpor", "Bonny", "Degema", "Eleme", "Okrika", "Ahoada East"],
  "Sokoto": ["Sokoto North", "Sokoto South", "Wamako", "Gwadabawa", "Tambuwal"],
  "Taraba": ["Jalingo", "Wukari", "Gashaka", "Bali", "Sardauna"],
  "Yobe": ["Damaturu", "Gashua", "Potiskum", "Nguru", "Geidam"],
  "Zamfara": ["Gusau", "Kaura Namoda", "Talata Mafara", "Anka", "Maradun"],
  "Abuja FCT": ["Garki", "Wuse", "Asokoro", "Maitama", "Gwagwalada", "Kuje", "Bwari", "Abuja Municipal"]
};
